#!/usr/bin/env python

import sys, itertools

def keyvals(me):
    for k in me:
        v = k.rstrip('\n').split('\t')
        yield v[0],v[1]

total = 0
correct = 0
try:
    for ((gsrc,gtgt),(rsrc,rtgt)) in itertools.izip(keyvals(open(sys.argv[1])),keyvals(open(sys.argv[2]))):
        if gsrc != rsrc:
            sys.stderr.write("guess and reference files do not appear to match\n")
            sys.stdout.write("0\t0\t0.0")
            sys.exit(1)
        total += 1
        if gtgt == rtgt:
            correct += 1
except:
    sys.stderr.write("something wrong with these files:%s\t%s\n" % (sys.argv[1],sys.argv[2]))
    sys.stdout.write("0\t0\t0.0")
    sys.exit(1)
sys.stdout.write('\t'.join(str(v) for v in (total,correct,'%.4f' % (float(correct)/total))) + '\n')

